language: java

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -e "CREATE USER 'test'@'%' IDENTIFIED BY 'qwerty';"
  - mysql -e 'CREATE DATABASE magnus_test;'
  - mysql -uroot magnus_test < MagnusServer/db_setup/db.sql

script:
  - cd MagnusServer
  - gradle build jar
  - cd ../MagnusStreamer
  - gradle build jar
